# Generated by Django 4.2.dev20230112122347 on 2023-01-30 23:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thePerfectLandlord', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('doc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('doc_path', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentItem',
            fields=[
                ('item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=30)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, default=datetime.date.today)),
                ('role', models.CharField(max_length=20)),
                ('reference_name', models.CharField(max_length=20)),
                ('reference_phone', models.IntegerField(default=0)),
                ('reference_email', models.EmailField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('feature_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('freq_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('freq_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='type',
            name='type_category',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.CreateModel(
            name='ResidentialItem',
            fields=[
                ('item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=30)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, default=datetime.date.today)),
                ('reference_name', models.CharField(max_length=20)),
                ('reference_phone', models.IntegerField(default=0)),
                ('reference_email', models.EmailField(blank=True, max_length=30)),
                ('residential_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='thePerfectLandlord.type')),
            ],
        ),
        migrations.CreateModel(
            name='ResidentialDetails',
            fields=[
                ('details_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('verified', models.BooleanField(default=False)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thePerfectLandlord.residentialitem')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thePerfectLandlord.user')),
            ],
        ),
        migrations.CreateModel(
            name='PublicDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('age', models.IntegerField(blank=True, default=0)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='thePerfectLandlord.user')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyLease',
            fields=[
                ('lease_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thePerfectLandlord.user')),
                ('contract_doc_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='thePerfectLandlord.document')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thePerfectLandlord.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyInspection',
            fields=[
                ('inspection_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(default=datetime.date.today)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thePerfectLandlord.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyFeatures',
            fields=[
                ('list_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('features_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thePerfectLandlord.feature')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thePerfectLandlord.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyApplication',
            fields=[
                ('application_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cover_letter', models.CharField(max_length=100)),
                ('preferred_start_date', models.DateField(default=datetime.date.today)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thePerfectLandlord.user')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thePerfectLandlord.property')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionRegistration',
            fields=[
                ('registration_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('inspection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thePerfectLandlord.propertyinspection')),
                ('inspector_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thePerfectLandlord.user')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeItem',
            fields=[
                ('item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('frequency_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='thePerfectLandlord.frequency')),
                ('income_doc_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='thePerfectLandlord.document')),
                ('income_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='thePerfectLandlord.type')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeDetails',
            fields=[
                ('details_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('verified', models.BooleanField(default=False)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thePerfectLandlord.incomeitem')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thePerfectLandlord.user')),
            ],
        ),
        migrations.CreateModel(
            name='IdentityItem',
            fields=[
                ('item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('identity_doc_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='thePerfectLandlord.document')),
                ('identity_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='thePerfectLandlord.type')),
            ],
        ),
        migrations.CreateModel(
            name='IdentityDetails',
            fields=[
                ('details_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('verified', models.BooleanField(default=False)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thePerfectLandlord.identityitem')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thePerfectLandlord.user')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentDetails',
            fields=[
                ('details_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('verified', models.BooleanField(default=False)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thePerfectLandlord.employmentitem')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thePerfectLandlord.user')),
            ],
        ),
    ]
