# Generated by Django 4.1.5 on 2023-02-01 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thePerfectLandlord', '0002_document_employmentitem_feature_frequency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedProperties',
            fields=[
                ('saved_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('saved_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Type',
            new_name='Choice',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='type_category',
            new_name='choice_category',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='type_id',
            new_name='choice_id',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='type_name',
            new_name='choice_name',
        ),
        migrations.RenameField(
            model_name='identityitem',
            old_name='identity_type',
            new_name='identity_choice',
        ),
        migrations.RenameField(
            model_name='incomeitem',
            old_name='frequency_type_id',
            new_name='frequency_id',
        ),
        migrations.RenameField(
            model_name='incomeitem',
            old_name='income_type_id',
            new_name='income_choice_id',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='property_type',
            new_name='property_choice',
        ),
        migrations.RenameField(
            model_name='residentialitem',
            old_name='residential_type_id',
            new_name='residential_choice_id',
        ),
        migrations.AlterField(
            model_name='employmentdetails',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employmentitem',
            name='end_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employmentitem',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='identitydetails',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incomedetails',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inspectionregistration',
            name='inspector_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='landlord_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertyapplication',
            name='candidate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertyapplication',
            name='preferred_start_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='propertyinspection',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='propertylease',
            name='candidate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertylease',
            name='end_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='propertylease',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='publicdetails',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='residentialdetails',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='residentialitem',
            name='end_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='residentialitem',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='savedproperties',
            name='property_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thePerfectLandlord.property'),
        ),
        migrations.AddField(
            model_name='savedproperties',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
