# Generated by Django 4.1.5 on 2023-02-01 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thePerfectLandlord', '0004_rename_incomedetails_employmentdetail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityType',
            fields=[
                ('type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeType',
            fields=[
                ('type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ResidentialType',
            fields=[
                ('type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='identityitem',
            name='identity_choice',
        ),
        migrations.RemoveField(
            model_name='incomeitem',
            name='income_choice_id',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_choice',
        ),
        migrations.RemoveField(
            model_name='residentialitem',
            name='residential_choice_id',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.AddField(
            model_name='identityitem',
            name='identity_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='thePerfectLandlord.identitytype'),
        ),
        migrations.AddField(
            model_name='incomeitem',
            name='income_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='thePerfectLandlord.incometype'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='thePerfectLandlord.propertytype'),
        ),
        migrations.AddField(
            model_name='residentialitem',
            name='residential_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='thePerfectLandlord.residentialtype'),
        ),
    ]
