# Generated by Django 4.1.5 on 2023-02-01 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thePerfectLandlord', '0005_identitytype_incometype_propertytype_residentialtype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='propertylease',
            name='contract_doc_id',
        ),
        migrations.AddField(
            model_name='propertylease',
            name='contract_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='thePerfectLandlord.contract'),
        ),
    ]
