# Generated by Django 4.1.5 on 2023-02-01 02:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thePerfectLandlord', '0006_contract_remove_propertylease_contract_doc_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PublicDetail',
            new_name='UserProfile',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_id',
            new_name='user',
        ),
    ]
